{{- if or .Values.sessionKey.value .Values.upstreamApiKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maskflow-gateway.fullname" . }}
  labels:
    {{- include "maskflow-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.sessionKey.value }}
  session-key: {{ .Values.sessionKey.value | quote }}
  {{- end }}
  {{- if .Values.upstreamApiKey.value }}
  upstream-api-key: {{ .Values.upstreamApiKey.value | quote }}
  {{- end }}
{{- end -}}
